// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjwEfKP8VfRkb7r-CFGhxjuho2OyxvpsI',
    appId: '1:999305189881:web:9a2cc114f696696f4c8528',
    messagingSenderId: '999305189881',
    projectId: 'a-visa-experts-eeac1',
    authDomain: 'a-visa-experts-eeac1.firebaseapp.com',
    databaseURL: 'https://a-visa-experts-eeac1-default-rtdb.firebaseio.com',
    storageBucket: 'a-visa-experts-eeac1.firebasestorage.app',
    measurementId: 'G-8M37J90SVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB18PkGKh1FOAYbkuV5W_sk4BR_Ei7zOc',
    appId: '1:999305189881:android:94d1cdae0d6c7a384c8528',
    messagingSenderId: '999305189881',
    projectId: 'a-visa-experts-eeac1',
    databaseURL: 'https://a-visa-experts-eeac1-default-rtdb.firebaseio.com',
    storageBucket: 'a-visa-experts-eeac1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOU3GirxEqOy8H4cH-rBXuYPD4E4V2PFo',
    appId: '1:999305189881:ios:001911a16821b1be4c8528',
    messagingSenderId: '999305189881',
    projectId: 'a-visa-experts-eeac1',
    databaseURL: 'https://a-visa-experts-eeac1-default-rtdb.firebaseio.com',
    storageBucket: 'a-visa-experts-eeac1.firebasestorage.app',
    iosClientId: '999305189881-o9vtvghdqo5cmq9mq0gp6fq48sucrn9n.apps.googleusercontent.com',
    iosBundleId: 'com.avisaexperts.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjwEfKP8VfRkb7r-CFGhxjuho2OyxvpsI',
    appId: '1:999305189881:web:a5acc7d3d3e5a0214c8528',
    messagingSenderId: '999305189881',
    projectId: 'a-visa-experts-eeac1',
    authDomain: 'a-visa-experts-eeac1.firebaseapp.com',
    databaseURL: 'https://a-visa-experts-eeac1-default-rtdb.firebaseio.com',
    storageBucket: 'a-visa-experts-eeac1.firebasestorage.app',
    measurementId: 'G-L63S5K47JW',
  );
}
